language: es
site_title: Blas Fern치ndez
site_description: Ingeniero de Software Paraguayo 游왫릖, trabajando con Python, Java, PostgreSQL, MySQL, Oracle, Django, React, JavaScript, FastAPI y m치s.
site_name: blasferna.com
domain: blasferna.com
author_name: Blas Fern치ndez
author_email: blasferna@gmail.com
author_alias: blasferna
author_avatar: /static/img/profile.jpeg
author_website: https://github.com/blasferna 
twitter_username: blasfernac
posts_per_page: 5

projects:
  django-calculation:
    title: django-calculation
    summary: Haz c치lculos simples en formularios django
    icon:  /static/img/django.png
    url_text: github.com
    url: https://github.com/blasferna/django-calculation
  radio:
    title: VanillaJS Radio
    summary: Mi reproductor de radio personal escrito en vanilla js
    icon:  /static/img/js.png
    url_text: blasferna.github.io/radio/
    url: https://blasferna.github.io/radio/
  blasferna.com:
    title: blasferna.com
    summary: Mi blog personal y portafolio escrito en Python y Tailwindcss
    icon:  /static/img/python.png
    url_text: github.com
    url: https://github.com/blasferna/blasferna.com
  django-crispy-formset-modal:
    title: django-crispy-formset-modal
    summary: 游닇 Una aplicaci칩n de Django para administrar formsets con modales usando Django Crispy Forms
    icon:  /static/img/django.png
    url_text: github.com
    url: https://github.com/blasferna/django-crispy-formset-modal
  lazynews:
    title: Lazynews
    summary: Plataforma de resumen de noticias basada en inteligencia artificial
    icon:  /static/img/react.png
    url_text: ailazynews.vercel.app
    url: https://ailazynews.vercel.app
  aiskeleton:
    title: AISkeleton
    summary: Genera esqueletos para tu c칩digo HTML usando IA
    icon:  /static/img/react.png
    url_text: aiskeleton.vercel.app
    url: https://aiskeleton.vercel.app

i18n:
  read_more: Leer m치s
  home: Inicio
  articles: Art칤culos
  projects: Proyectos
  home_title: Blas Fern치ndez
  home_summary: Ingeniero de Software Paraguayo 游왫릖, trabajando con Python, Java, PostgreSQL, MySQL, Oracle, Django, React, JavaScript, FastAPI y m치s.
  all_rights_reserved: Todos los derechos reservados
  previous: Anterior
  next: Siguiente
  something_missing: Falta algo.
  sorry_we_cant_find_that_page: Lo sentimos, no podemos encontrar esa p치gina. Encontrar치 mucho para explorar en la p치gina de inicio. 
  back_to_homepage: Ir al inicio
  share: Compartir
  copy_url: copiar URL
  url_copied:  URL copiado!
  tag: Etiqueta
  tags: Etiquetas

giscus:
  enabled: true
  repo: blasferna/blasferna.com
  repo_id: R_kgDOJdq81g
  category: General
  category_id: DIC_kwDOJdq81s4Cjc8U
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  crossorigin: anonymous
