language: en
site_title: Blas FernÃ¡ndez
site_description: A place for Blas to share his thoughts and experiences.
author_name: Blas FernÃ¡ndez
author_email: blasferna@gmail.com
author_alias: blasferna
posts_per_page: 5

projects:
  django-calculation:
    title: django-calculation
    summary: Make simple calculations in django forms
    icon:  /static/img/django.png
    url_text: github.com
    url: https://github.com/blasferna/django-calculation
  radio:
    title: VanillaJS Radio
    summary: My personal radio player written in vanilla js
    icon:  /static/img/js.png
    url_text: blasferna.github.io/radio/
    url: https://blasferna.github.io/radio/
  blasferna.com:
    title: blasferna.com
    summary: My personal blog and portfolio writen in Python and Tailwindcss
    icon:  /static/img/python.png
    url_text: github.com
    url: https://github.com/blasferna/blasferna.com

i18n:
  read_more: Read more
  about: About
  articles: Articles
  projects: Projects
  about_title: Software Engineer
  about_summary: Iâ€™m Blas fernÃ¡ndez, a software Engineer, working with ðŸ’— Python, Java, Postgresql, MySQL, Oracle and much more.
  all_rights_reserved: All rights reserved

