language: en
site_title: Blas FernÃ¡ndez
site_description: Software Engineer, working with Python, Java, Postgresql, MySQL, Oracle and much more.
site_name: new.blasferna.com
domain: new.blasferna.com
author_name: Blas FernÃ¡ndez
author_email: blasferna@gmail.com
author_alias: blasferna
author_avatar: /static/img/profile.jpeg
author_website: https://github.com/blasferna
twitter_username: blasfernac
posts_per_page: 5

projects:
  django-calculation:
    title: django-calculation
    summary: Make simple calculations in django forms
    icon:  /static/img/django.png
    url_text: github.com
    url: https://github.com/blasferna/django-calculation
  radio:
    title: VanillaJS Radio
    summary: My personal radio player written in vanilla js
    icon:  /static/img/js.png
    url_text: blasferna.github.io/radio/
    url: https://blasferna.github.io/radio/
  blasferna.com:
    title: blasferna.com
    summary: My personal blog and portfolio written in Python and Tailwindcss
    icon:  /static/img/python.png
    url_text: github.com
    url: https://github.com/blasferna/blasferna.com

i18n:
  read_more: Read more
  home: Home
  articles: Articles
  projects: Projects
  home_title: Software Engineer
  home_summary: Iâ€™m Blas FernÃ¡ndez, a software Engineer, working with ðŸ’— Python, Java, Postgresql, MySQL, Oracle and much more.
  all_rights_reserved: All rights reserved
  previous: Previous
  next: Next
  something_missing: Something's missing.
  sorry_we_cant_find_that_page: Sorry, we can't find that page. You'll find lots to explore on the home page. 
  back_to_homepage: Back to Homepage
  share: Share
  copy_url: copy URL
  url_copied:  URL copied!
